### ISSUE TITLE
TypeError: argument 1 must be string, not NetworkInterface

### ISSUE THREAD

**Issue by PeeKa04Boo** [DanMcInerney/wifijammer#114]
Getting this error: 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wifijammer", line 243, in channel_hop
    deauth(monchannel)
  File "wifijammer", line 287, in deauth
    send(p, inter=float(args.timeinterval), count=int(args.packets))
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 429, in send      
    **kargs
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 397, in _send     
    realtime=realtime, return_packets=return_packets)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 360, in __gen_send
    s.send(p)
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 605, in send    
    self.outs.bind(sdto)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
TypeError: argument 1 must be string, not NetworkInterface

I tried to use the SSID instead of MAC but still the same, 
I tried to downgrade scapy from 2.4.5 to 2.3.3 but the same.

**Comment by PeeKa04Boo** [comment]
hey guys I'm really sorry for the late response. @jepst is right @jurosic , I was able to get it to work by downgrading scapy as well. Although, I haven't used this after I got it to work because as I was looking for a fix for this issue, I saw a recommendation of using bettercap so I started using that instead
