### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by deepu8012** [DanMcInerney/wifijammer#119]
![Screenshot at 2022-07-12 17-31-43](https://user-images.githubusercontent.com/109132224/178424979-a25db094-dc46-4bd6-802d-3e9c579d04da.png)
![Screenshot at 2022-07-12 17-31-43](https://user-images.githubusercontent.com/109132224/178425032-3e65e269-61e3-4808-85ab-273080c9264a.png)

**Comment by deepu8012** [comment]
Traceback (most recent call last):
  File "/home/deepu/Desktop/wifijammer2.py", line 444, in <module>
    mon_iface = get_mon_iface(args)
  File "/home/deepu/Desktop/wifijammer2.py", line 105, in get_mon_iface
    monitors, interfaces = iwconfig()
  File "/home/deepu/Desktop/wifijammer2.py", line 127, in iwconfig
    for line in proc.communicate()[0].split('\n'):
TypeError: a bytes-like object is required, not 'str'
