### ISSUE TITLE
Start with Python2/3 result in str() errors

### ISSUE THREAD

**Issue by Flerov** [DanMcInerney/wifijammer#125]
Python3 not working at all. Python2 finds some Networks before crash
Trying to start in Python3 results in: [
Traceback (most recent call last):
  File "./wifijammer", line 476, in <module>
    mon_iface = get_mon_iface(args)
  File "./wifijammer", line 117, in get_mon_iface
    interface = get_iface(interfaces)
  File "./wifijammer", line 160, in get_iface
    for line in proc.communicate()[0].split('\n'):
TypeError: a bytes-like object is required, not 'str'
]

In Python2 results in: [
[*] Finding the most powerful interface...
[+] Networks discovered by wlan1: 0
[+] Networks discovered by wlan0: 13
[+] Starting monitor mode off wlan0
Error for wireless request "Set Mode" (8B06) :
    SET failed on device wlan0 ; Operation not supported.
Traceback (most recent call last):
  File "./wifijammer", line 478, in <module>
    mon_MAC = mon_mac(mon_iface)
  File "./wifijammer", line 199, in mon_mac
    info = fcntl.ioctl(s.fileno(), 0x8927, struct.pack('256s', bytes(mon_iface, 'utf-8')[:15]))
TypeError: str() takes at most 1 argument (2 given)
]

Any suggestions?

**Comment by davidm71** [comment]
Change lines 199 +200 in the wifijammer source code to this:
info = fcntl.ioctl(s.fileno(), 0x8927, struct.pack('256s', bytes(mon_iface).encode('utf-8')[:15]))
mac = ':'.join('%02x' % ord(b) for b in info[18:24])

**Comment by Rukasyywyw** [comment]
> Change lines 199 +200 in the wifijammer source code to this: info = fcntl.ioctl(s.fileno(), 0x8927, struct.pack('256s', bytes(mon_iface).encode('utf-8')[:15])) mac = ':'.join('%02x' % ord(b) for b in info[18:24])






raceback (most recent call last):
  File "/home/kali/wifijammer/wifijammer", line 478, in <module>
    mon_MAC = mon_mac(mon_iface)
  File "/home/kali/wifijammer/wifijammer", line 199, in mon_mac
    info = fcntl.ioctl(s.fileno(), 0x8927, struct.pack('256s', bytes(mon_iface).encode('utf-8')[:15]))
TypeError: string argument without an encoding

**Comment by davidm71** [comment]
Worked for me.

**Comment by willlem** [comment]
With a raspberry pi3 and raspian I get the same error as Rukadsyywyw.  with a new kali installation i get the same error as Rukadsyywyw. who can help me to solve this error?
