### ISSUE TITLE
'utf-8' codec can't decode byte 0x92 in position 14: invalid start byte

### ISSUE THREAD

**Issue by MR-Diamond** [DanMcInerney/wifijammer#126]
Hi, I attempt to run wifijammer in Termux; I have installed python, scapy and iwconfig.
But as I execute `tsudo python wifijammer` I got:

```
Traceback (most recent call last):
  File "wifijammer", line 476, in <module>
    mon_iface = get_mon_iface(args)
  File "wifijammer", line 106, in get_mon_iface       monitors, interfaces = iwconfig()
  File "wifijammer", line 129, in iwconfig            for line in proc.communicate()[0].decode().split('\n'):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 14: invalid start byte
```

Am I miss something?

**Comment by davidm71** [comment]
Change lines 199 +200 in the wifijammer source code to this:
info = fcntl.ioctl(s.fileno(), 0x8927, struct.pack('256s', bytes(mon_iface).encode('utf-8')[:15]))
    mac = ':'.join('%02x' % ord(b) for b in info[18:24])

**Comment by MR-Diamond** [comment]
Done, but now I get a different error:

![wifijammer_error](https://user-images.githubusercontent.com/32249442/209563201-4323bcdc-8383-4105-ab42-bb1424f25ee2.png)

**Comment by davidm71** [comment]
You must have made a mistake typing in the correction. Python follows strict indentation rules. Everything must line up as it was before. Start over.

**Comment by MR-Diamond** [comment]
Fixed, but I still get an error about utf-8:

![Error_2](https://user-images.githubusercontent.com/32249442/209564158-68dc5821-3c9f-4cae-8a3e-4ca5be416f81.png)

**Comment by davidm71** [comment]
Idk. I got mine working on a Rasp Pi 2B with Python 2.71. Could be your version of Python is the issue.

**Comment by davidm71** [comment]
Change line 317 to:
 print('['+T+'*'+W+'] '+O+ca[0]+W +' - '+O+ca[1]+
                       W+' - '+ca[2].ljust(2)+' - '+T+ca[3].decode("ascii")+W)
Line 325 to:
 print('['+T+'*'+W+'] '+O+ap[0]+W+' - ' +
                  ap[1].ljust(2)+' - '+T+ap[2].decode("ascii")+W)

And then manually install the latest version of Scapy:
wget --trust-server-names https://github.com/secdev/scapy/archive/master.zip   # or wget -O master.zip https://github.com/secdev/scapy/archive/master.zip
unzip master.zip
cd scapy
sudo python setup.py install

**Comment by DanMcInerney** [comment]
@davidm71 or @MR-Diamond can you throw me a PR with that change.

**Comment by davidm71** [comment]
PR?
