### ISSUE TITLE
wifijammer :: ERROR: Loading module scapy.layers.mspac

### ISSUE THREAD

**Issue by MedAly666** [DanMcInerney/wifijammer#127]
hi ,
i cloned wifijammer on my debian machine and that is the error message

`ERROR: Loading module scapy.layers.mspac
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.5.0-py2.7.egg/scapy/main.py", line 156, in _load
    mod = importlib.import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.5.0-py2.7.egg/scapy/layers/mspac.py", line 482, in <module>
    class CLAIM_ENTRY(NDRPacket):
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.5.0-py2.7.egg/scapy/layers/mspac.py", line 486, in CLAIM_ENTRY
    NDRInt3264EnumField("Type", 0, CLAIM_TYPE),
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.5.0-py2.7.egg/scapy/layers/dcerpc.py", line 1102, in __init__
    _NDREnumField(*args, **kwargs), align=(2, 4)
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.5.0-py2.7.egg/scapy/fields.py", line 2467, in __init__
    keys = list(enum)  # type: ignore
TypeError: 'type' object is not iterable
Traceback (most recent call last):
  File "wifijammer", line 478, in <module>
    mon_MAC = mon_mac(mon_iface)
  File "wifijammer", line 199, in mon_mac
    info = fcntl.ioctl(s.fileno(), 0x8927, struct.pack('256s', bytes(mon_iface, 'utf-8')[:15]))
TypeError: str() takes at most 1 argument (2 given)`

**Comment by gconelhero** [comment]
> hi , i cloned wifijammer on my debian machine and that is the error message
> 
> `ERROR: Loading module scapy.layers.mspac Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/scapy-2.5.0-py2.7.egg/scapy/main.py", line 156, in _load mod = importlib.import_module(module) File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module __import__(name) File "/usr/local/lib/python2.7/dist-packages/scapy-2.5.0-py2.7.egg/scapy/layers/mspac.py", line 482, in <module> class CLAIM_ENTRY(NDRPacket): File "/usr/local/lib/python2.7/dist-packages/scapy-2.5.0-py2.7.egg/scapy/layers/mspac.py", line 486, in CLAIM_ENTRY NDRInt3264EnumField("Type", 0, CLAIM_TYPE), File "/usr/local/lib/python2.7/dist-packages/scapy-2.5.0-py2.7.egg/scapy/layers/dcerpc.py", line 1102, in __init__ _NDREnumField(*args, **kwargs), align=(2, 4) File "/usr/local/lib/python2.7/dist-packages/scapy-2.5.0-py2.7.egg/scapy/fields.py", line 2467, in __init__ keys = list(enum) # type: ignore TypeError: 'type' object is not iterable Traceback (most recent call last): File "wifijammer", line 478, in <module> mon_MAC = mon_mac(mon_iface) File "wifijammer", line 199, in mon_mac info = fcntl.ioctl(s.fileno(), 0x8927, struct.pack('256s', bytes(mon_iface, 'utf-8')[:15])) TypeError: str() takes at most 1 argument (2 given)`

Type in the terminal:
```
sudo mkdir /usr/lib/python2.7/dist-packages/scapy
cd  /usr/lib/python3/dist-packages/
cp -avr scapy/* /usr/lib/python2.7/dist-packages/scapy

```
