### ISSUE TITLE
code isn't working some error occours 

### ISSUE THREAD

**Issue by Hammad914** [DanMcInerney/wifijammer#129]
python wifijammer      
[*] Monitor mode: wlan1mon - ec:08:**:**:**:**
Exception in thread Thread-1 (channel_hop):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hmd6981/wifijammer/wifijammer", line 240, in channel_hop
    for line in proc.communicate()[1].split('\n'):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'

**Comment by imarkskinner** [comment]
Getting the same word for word so wont post the error here again. 

My steps:
Download latest kali iso and install into Gnome boxes.
Clone wifijammer from git
install python2.7 & 3 just incase, install scapy3 python from apt, again, not sure if the wifijammer or setup script includes it but cant have too much python
Run setup.py build and then install
Run sudo python ./wifijammer
Error shows.

Not an expert so tried python3 and python2 because I was just mashing my keyboard in desperation, this error is with python3
