### ISSUE TITLE
Crash [Kali 3.0]

### ISSUE THREAD

**Issue by alekssobolewski** [DanMcInerney/wifijammer#41]
[+] wlan0 channel: 1

```
  Access Points     ch   ESSID
```

[*] 11:22:33:44:55:66 - 1  - Hot Cats

[!] Closing
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "wifijammer.py", line 190, in channel_hop
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

**Comment by DanMcInerney** [comment]
Will check this out in a bit, no access to a wifi card in the near future.
