### ISSUE TITLE
Error: Network is down

### ISSUE THREAD

**Issue by DeJung** [DanMcInerney/wifijammer#44]
After some time of running this script I get this error:

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "wifijammer.py", line 190, in channel_hop
    deauth(monchannel)
  File "wifijammer.py", line 235, in deauth
    send(p, inter=float(args.timeinterval), count=int(args.packets))
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 251, in send
    __gen_send(conf.L3socket(_args, *_kargs), x, inter=inter, loop=loop, count=count,verbose=verbose, realtime=realtime)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 234, in __gen_send
    s.send(p)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 389, in send
    self.outs.sendto(sx, sdto)
error: [Errno 100] Network is down

Any chances?

`

**Comment by JonathanJhon55** [comment]
Having the same myself @DanMcInerney  any fixes for this?

I use a TPlink w722n

**Comment by Zawadidone** [comment]
Me having the same

**Comment by DanMcInerney** [comment]
How long does it take before you receive that error? Is your internet going
out at the same time or are there no connection problems elsewhere?

**Comment by Ijlalh90** [comment]
After few minutes

**Comment by nionios2000** [comment]
I have the same problem

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/nionios/Επιφάνεια εργασίας/wifijammer.py", line 238, in channel_hop
    deauth(monchannel)
  File "/home/nionios/Επιφάνεια εργασίας/wifijammer.py", line 283, in deauth
    send(p, inter=float(args.timeinterval), count=int(args.packets))
  File "/home/nionios/.local/lib/python2.7/site-packages/scapy/sendrecv.py", line 269, in send
    realtime=realtime, return_packets=return_packets)
  File "/home/nionios/.local/lib/python2.7/site-packages/scapy/sendrecv.py", line 247, in __gen_send
    s.send(p)
  File "/home/nionios/.local/lib/python2.7/site-packages/scapy/arch/linux.py", line 404, in send
    self.outs.sendto(sx, sdto)
error: [Errno 100] Network is down

**Comment by pvescrubz** [comment]
It helped me : 
airmon-ng start wlan1 -> use jammer w/o problem :)

**Comment by MisterBianco** [comment]
This is often due to cards leaving monitor mode unexpectedly...

**Comment by MisterBianco** [comment]
get a dev branch of scapy and it either wont happen or will happen alot less.
