### ISSUE TITLE
Crash Exception in thread Thread-1:

### ISSUE THREAD

**Issue by JustMev** [DanMcInerney/wifijammer#63]
Log after it crashes
---------------------------------------------------------------

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wifijammer", line 238, in channel_hop
    deauth(monchannel)
  File "wifijammer", line 283, in deauth
    send(p, inter=float(args.timeinterval), count=int(args.packets))
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 269, in send
    realtime=realtime, return_packets=return_packets)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 247, in __gen_send
    s.send(p)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 404, in send
    self.outs.sendto(sx, sdto)
error: [Errno 100] Network is down

[!] Closing
root@kali:~/wifijammer#

**Comment by unicoded** [comment]
I have an idea about this.
The issue is that NetworkManager is conflicting with normal operation. If you kill NetworkManager, there aren't any issues like above that I experienced. So add the following code to when it begins scanning networks:
Right after this:
# Start monitor mode on a wireless interface
        print '['+G+'*'+W+'] Finding the most powerful interface...'
        
Add this:
        *os.system('pkill NetworkManager')*
Then at the end, include this:
Right after this:
def stop(signal, frame):
    if monitor_on:
Include this:
        *os.system('service network-manager restart')*
This way you close and reopen the NetworkManager automatically.

**Comment by thatuser-kali** [comment]
Added the code and iam still getting the error.

**Comment by MisterBianco** [comment]
This often happens if the card unexpectedly exits monitor mode. however i wouldnt be able to determine why it is happening.
